### ISSUE TITLE
Upgrade to hiredis v1.0.0 with SSL support

### ISSUE THREAD

**Issue by jcohen02** [rwinlib/hiredis#1]
Hi @jeroen, @richfitz,

Is there any chance we could update this to use hiredis v1.0.0 (and include SSL support)? 

I prototyped some updates to [redux](https://github.com/richfitz/redux) a while ago so that I could create an SSL connection to redis from R via redux and hiredis. At the time the SSL updates in [hiredis](https://github.com/redis/hiredis) were in master but hadn't made it into a release and there didn't seem to be a straightforward route to a clean install process so that redux could pull the necessary dependencies to get an SSL build of hiredis when installed from CRAN. Now that hiredis has reached 1.0.0 with the SSL support included, I thought I'd revisit this.

It looks like there are various breaking changes between hiredis 0.9.2 that is currently used here and 1.0.0 so I don't know what the best approach to use here is? Can the repo simply be tagged v0.9.2 and then anyone wanting the libraries from the previous version can pull that tag?

I've got the changes in place in the [feature/v1ssl](https://github.com/jcohen02/hiredis-1/tree/feature/v1ssl) branch of my fork if you want to take a look.
It builds fine using a mingw64 toolchain from rtools40 but I think some more testing is required, however, if you're happy in principle to make this update, I could open a PR.

Many thanks,
Jeremy

**Comment by jeroen** [comment]
Would you be willing to contribute this to https://github.com/r-windows/rtools-packages ?

**Comment by jcohen02** [comment]
In principle, yes (if I can work things out!) - I'll take a look.

**Comment by jeroen** [comment]
OK let me know if you get stuck, I can try to help.

**Comment by jcohen02** [comment]
@jeroen I guess this discussion should move to an issue in r-windows/rtools-packages but for now, I have what I think is a working [hiredis package](https://github.com/jcohen02/rtools-packages/commit/9faba659168a4a6c82cc025c4e4b04128da493a7) in the [feature/hiredis](https://github.com/jcohen02/rtools-packages/tree/package/hiredis) branch of [my rtools-packages fork](https://github.com/jcohen02/rtools-packages).

This is my first attempt at a mingw package so if you have a chance to take a look, I'd appreciate any feedback or advice on any fundamental errors I've made!

The testing is a bit of an issue - the hiredis test tool needs to test against a redis deployment. I've done this manually testing against a standard redis deployment and via SSL using stunnel in front of redis. There are a couple of tests that fail due to attempting to connect via a unix socket but the core tests that use standard port-based network connections pass via both standard and SSL connections. However, I don't think running the tests as part of the package build is practical given the need for a redis/stunnel deployment.

When I run `makepkg-mingw --syncdeps` the the build process builds two `.a` files and the `hiredis-test` tool which links against these libraries so I'm assuming they must be building correctly given that the testing tool then works (running manually rather than during the build as highlighted above). Ultimately, I get two `.xz` files out, one for the `i686` package and one for the `x86_64` package.

The only remaining thing I'm unsure about is `pkg-config`. There's a bunch of `pkg-config` setup done in the hiredis CMake build file and the `.pc` files are created but I tried running pkg-config.exe in my `mingw64` environment after the package install and it's telling me it can't find details of the package. Should the `.pc` files be placed somewhere else in `rtools-packages` tree?

Many thanks.

**Comment by jeroen** [comment]
Can you send a pull request to rtools-packages? Then we look at the CI and go from there.

**Comment by jeroen** [comment]
Uploaded binaries-> https://github.com/rwinlib/hiredis/releases/tag/v1.0.0

**Comment by richfitz** [comment]
Thanks both for looking at this - does this work with the redux that is on CRAN?

**Comment by jeroen** [comment]
Redux PR here: https://github.com/richfitz/redux/pull/35

**Comment by jeroen** [comment]
@richfitz only one way to find out :) I don't think there are any breaking changes by updating hiredis, but perhaps once @jcohen02 starts adding ssl features, you need to skip unit tests on servers that do not support this.

**Comment by richfitz** [comment]
Thanks Jeroon, this looks great
